### ISSUE TITLE
RBot/ts issues

### ISSUE THREAD

**Issue by ky28059** [ky28059/RBot#14]
RBot ts is running into some wacky type issues and since I have asked everyone else to no avail I will just post them here and hope someone has the answer!

<hr>

- [ ] Something is wacky with math.ts's parser

<img width="521" alt="math" src="https://user-images.githubusercontent.com/60120929/118895060-4cfcdd00-b8ba-11eb-9b5d-6a14e63099c4.png">

According to the docs for both [configuration](https://mathjs.org/docs/core/configuration.html) and [parsing](https://mathjs.org/docs/expressions/parsing.html#parser) this should be fine, and in practice (running the committed version of RBot in js) it's also fine, but for some reason ts is malding.

<hr>

- [ ] Weird `never` type in tokenManager

<img width="771" alt="never" src="https://user-images.githubusercontent.com/60120929/118895563-41f67c80-b8bb-11eb-84a5-100f7ffdfbda.png">

Somehow `tag[field]` is of type `never`, which is very strange. `tag` should be a `GuildInstance`, which is essentially the type of the guild object currently in `Guild.js` but converted to ts using the sequelize.define steps [here](https://sequelize.org/master/manual/typescript.html).

This is not a comprehensive list.

**Comment by ky28059** [comment]
This is stale, so I'll archive TS changes on another branch and not worry about them.

**Comment by SheepTester** [comment]
Re first one, according to the index.d.ts, `create` returns a `Partial`:

```ts
  interface FactoryDependencies {
    create: (factories: FactoryFunctionMap, config?: ConfigOptions) => Partial<MathJsStatic>;
```

https://github.com/josdejong/mathjs/blob/0dfc1482ac91c1bc340e93cbc08f7402d5fd85ff/types/index.d.ts#L2393

A `Partial`'s properties [are all optional](https://www.typescriptlang.org/docs/handbook/utility-types.html#partialtype), hence why `math.parser` could be undefined.

**Comment by SheepTester** [comment]
You can perhaps just check if it's undefined and then throw an error if it's undefined (or `return` if you don't trust it):

```ts
if (!math.parser) {
  throw new TypeError('math.parser is undefined??')
}
```

After that point, `math.parser` should not be undefined
