### ISSUE TITLE
rewrite in java or a high-level language

### ISSUE THREAD

**Issue by chop0** [ky28059/RBot#6]

**Comment by alecpetridis** [comment]
i can do this one if you want

**Comment by ky28059** [comment]
but why

**Comment by SheepTester** [comment]
is javascript insufficiently high-level for you

**Comment by alecpetridis** [comment]
JavaScript isn't high level its interpreted 😔🤪🤪🤪🤪🤪

**Comment by UnsignedByte** [comment]
Write it in matlab to please our god chop0

**Comment by chop0** [comment]
write it in powerpoint
